import fs from 'fs';
import path from 'path';
import chalk from 'chalk';

/**
 * Motor de Plantillas y Cumplimiento de Estilos (Template Engine)
 * Enforces "Ruth Compliant" styling and other global formatting rules.
 */
export class TemplateEngine {
    constructor() {
        this.styles = {
            margins: "Top 5cm, Left 3.5cm, Right 3cm, Bottom 2.5cm",
            font: "Arial 12pt (11pt for quotes)",
            header: "3-column header starting on page 2 (Logo, Title, Page Number)",
            footer: "No footers",
            idioms: "cursive for idioms/colloquialisms"
        };
    }

    /**
     * Intercepts document generation to enforce styling.
     * @param {string} rawContent Content generated by LLM (Markdown or JSON)
     * @param {string} format 'text', 'html', or 'docx'
     * @returns {string} Assembled content with styling
     */
    applyRuthCompliantStyles(rawContent, format = 'markdown') {
        let content = rawContent;
        
        // Try parsing JSON if rawContent is JSON string
        try {
            const match = rawContent.match(/```json\n([\s\S]*?)\n```/) || rawContent.match(/^{([\s\S]*?)}$/);
            const jsonStr = match ? (match[1] ? match[0].replace(/```json\n|\n```/g, '') : rawContent) : rawContent;
            if (jsonStr.trim().startsWith('{') || jsonStr.trim().startsWith('[')) {
                const data = JSON.parse(jsonStr);
                content = this.assembleFromData(data);
            }
        } catch (e) {
            // Not JSON, continue with raw content
        }

        // Si el contenido parece ser un acta o un reporte formal (heurística simple)
        if (content.toLowerCase().includes('acta') || content.toLowerCase().includes('reporte formal') || format === 'formal') {
            return `---
metadata:
  styling: "Ruth Compliant"
  margins: "${this.styles.margins}"
  font: "${this.styles.font}"
---
# Documento (Estilo Aplicado)
> Nota de Cumplimiento: Este documento ha sido estructurado bajo el manual de estilo "Ruth Compliant" (Márgenes NTC, Arial 12pt, portada reactiva, etc.).
> [Excel Tracking Matrix: Update to 'En F' (En Firma) upon finalization]

${content}
`;
        }

        return content;
    }

    assembleFromData(data) {
        let text = "";
        if (data.title) text += `# ${data.title}\n\n`;
        if (data.sections) {
            for (const sec of data.sections) {
                text += `## ${sec.title}\n${sec.content}\n\n`;
            }
        }
        return text || JSON.stringify(data, null, 2);
    }
    
    /**
     * Genera instrucciones para que el LLM devuelva JSON en vez de texto plano
     */
    getSystemPrompt() {
        return `
[INSTRUCCIÓN DE ESTILO - RUTH COMPLIANT]:
Debes estructurar tu salida como JSON crudo con los siguientes campos recomendados:
{
  "title": "Título del documento",
  "sections": [{"title": "Sección", "content": "Contenido"}]
}
El Template Engine se encargará del ensamblaje (márgenes NTC, Arial 12pt, sin pie de página).
Use cursiva (Markdown _texto_) para idiomas/coloquialismos.
`;
    }
}

export const templateEngine = new TemplateEngine();